---
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang
    environment:
      GO111MODULE: 'on'
    steps:
      - checkout
      - run: go version
      - run: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.15.0
      - run: bin/golangci-lint run
      - run: go test -v ./...
